# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('eventDetails', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userUniq', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('userImageUrlLarge', models.URLField(blank=True, max_length=500)),
                ('userImageUrlThumb', models.URLField(blank=True, max_length=500)),
                ('userName', models.CharField(blank=True, max_length=500)),
                ('userEmailfb', models.CharField(max_length=500, unique=True)),
                ('userIdfb', models.CharField(max_length=500, unique=True)),
                ('userAccessTokenfb', models.CharField(default='', max_length=500)),
                ('userCreatedTime', models.DateTimeField(verbose_name='User Created')),
                ('fbTotalFriends', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('userIdfb', models.CharField(max_length=100)),
                ('frUniq', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('time', models.DateTimeField(verbose_name='Friend Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeConnectApp.User')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeConnectApp.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeConnectApp.User'),
        ),
    ]
