# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WeConnectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('time', models.DateTimeField(verbose_name='Event Signed Up')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeConnectApp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='EventCreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 6, 24, 49, 204046, tzinfo=utc), verbose_name='Event Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='TotalEventTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='eventImage',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='eventName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
