# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeConnectApp', '0002_auto_20160402_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventExpired',
            field=models.BooleanField(default=False),
        ),
    ]
